site_name: GoElites Wiki
repo_url: https://github.com/y1n/GoElites.Wiki
pages:
- Inicio: index.md
- Principales:

    - Reglas de la Comunidad: CommunityPrinciples/CommunityGuidelines.md
    - Temas de soporte: CommunityPrinciples/SupportGuidelines.md
    
- Antes de comenzar:

    - Installing GoElites: GettingStarted/Installation.md
    - Características explicadas: GettingStarted/Features.md
    - Campeones que admite GoElites: GettingStarted/SupportedChampions.md
    - Preguntas Frecuentes: GettingStarted/FrequentlyAskedQuestions.md
    
- Solución de Problemas:

    - Como reportar un problema: Troubleshooting/TroubleshootingReportGuide.md
    - Soporte WEB: Troubleshooting/WebsiteTroubleshooting.md
    - Soporte de Aplicación: Troubleshooting/ApplicationTroubleshooting.md
    
theme: readthedocs
